#
#
# date: 2019/11/28
# authors: Roger Shanahan

all: polynomial
		
polynomial: polynomial.c
		gcc -Wall -ggdb -std=c11 o polynomial assignment.h assignment.c assignmentMain.c

clean:
		rm *~ *# polynomial

